version: '3.8'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: gitlab.example.com
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
    volumes:
      - './config.rb:/etc/gitlab/gitlab.rb:ro'
      - 'gitlab-data:/var/opt/gitlab'
      - 'gitlab-logs:/var/log/gitlab'
      - 'gitlab-config:/etc/gitlab'
    env_file:
      - .env
    depends_on:
      - gitlab-postgres
      - gitlab-redis

  gitlab-postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: "${GITLAB_POSTGRES_DB}"
      POSTGRES_USER: "${GITLAB_POSTGRES_USER}"
      POSTGRES_PASSWORD: "${GITLAB_POSTGRES_PASSWORD}"
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'

  gitlab-redis:
    image: redis:7
    command: [ "redis-server", "--requirepass", "${GITLAB_REDIS_PASSWORD}" ]
    volumes:
      - 'redis-data:/data'

volumes:
  gitlab-data:
  gitlab-logs:
  gitlab-config:
  postgres-data:
  redis-data:
