services:
  minio:
    image: quay.io/minio/minio:RELEASE.2023-12-02T10-51-33Z
    container_name: minio_server
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - app-network
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD-SHELL", "mc alias set health_check http://localhost:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY} && mc ready health_check"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s 
  create-minio-buckets:
    image: minio/mc
    container_name: minio_init
    networks:
      - app-network
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ./init-buckets.sh:/init-buckets.sh:ro
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    entrypoint: ["/bin/sh", "/init-buckets.sh"]

volumes:
  minio_data:

networks:
  app-network:
    driver: bridge
