services:
  minio:
    image: minio/minio:RELEASE.2024-10-01T00-00-00Z
    container_name: minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_REGION: ${MINIO_REGION}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001" 
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # MinIO console
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:9000/minio/health/ready || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 3

volumes:
  minio_data:
